#pragma once

#define BTN_PIN 12
#define LED_PIN 13
#define LED_COUNT 8
#define LED_BRIGHTNESS 200

#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASS "YOUR_WIFI_PASS"

#define BOT_TOKEN "YOUR_BOT_TOKEN"
#define CLIENT_ID "YOUR_CLIENT_ID"
